import { getDailyDigest } from "../lib/api.js";
import { digestErrorMessage } from "../lib/digest.js";
import { useAsync } from "../lib/useAsync.js";

export function DigestPage() {
  const { data, error, loading, reload } = useAsync(async () => {
    try {
      return await getDailyDigest();
    } catch (err) {
      throw new Error(digestErrorMessage(err));
    }
  }, []);

  return (
    <>
      <div className="page-head">
        <h1>Daily digest</h1>
        <div className="actions">
          {data &&
            (data.generatedBy === "claude" ? (
              <span className="badge in">Generated by Claude</span>
            ) : (
              <span className="badge neutral">Statistical stub (no API key)</span>
            ))}
          <button type="button" className="secondary" onClick={reload} disabled={loading}>
            Refresh
          </button>
        </div>
      </div>

      {error && <div className="error-banner">{error}</div>}

      {loading ? (
        <p className="empty">Preparing today’s digest…</p>
      ) : (
        data && (
          <section className="card">
            <div className="digest-text">{data.digest}</div>
            <details style={{ marginBlockStart: "var(--space-4)" }}>
              <summary className="faint">Raw data behind this digest</summary>
              <pre className="mono raw-json">{JSON.stringify(data.data, null, 2)}</pre>
            </details>
          </section>
        )
      )}
    </>
  );
}
